### ISSUE TITLE
Regression - GetBucketPolicy in S3 client returns nil Policy object

### ISSUE THREAD

**Issue by meshuga** [aws/aws-sdk-go-v2#1151] opened 2021-02-23 16:55 UTC
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [API reference](https://docs.aws.amazon.com/sdk-for-go/v2/api/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-go-v2/issues) and didn't find any solution
  
**Describe the bug**

**Version of AWS SDK for Go?**
v1.2.0, v1.1.0 (worked in v0.24.0)

**Version of Go (`go version`)?**
go1.15.5

**To Reproduce (observed behavior)**
1. Create a bucket `bucket-with-policy`
2. Associate a sample bucket policy with a bucket (examples: https://docs.aws.amazon.com/AmazonS3/latest/userguide/example-bucket-policies.html)
3. Run below code
```go
svc := s3.NewFromConfig(config.LoadDefaultConfig(context.TODO()))
policy, err = svc.GetBucketPolicy(context.TODO(), &s3.GetBucketPolicyInput{
  Bucket: "bucket-with-policy"
})

println(*policy.Policy) // should print policy associated with a bucket

```
**Expected behavior**
Above code prints bucket policy. That does not happen.

**Additional context**
Blocker for migration https://github.com/GoogleCloudPlatform/terraformer/pull/806

**Comment by jasdel** [comment] 2021-02-26 19:11
Thanks for reporting this bug @meshuga. The issue looks to be with the model the SDK is using for Amazon S3 API does not decorate the operation's response correctly. https://github.com/aws/aws-sdk-go-v2/blob/187b72aa982df445964f734f4ff476f72f7519db/codegen/sdk-codegen/aws-models/s3.2006-03-01.json#L4282-L4292

The v1 SDK's old model decorated the Policy member as the payload correctly. https://github.com/aws/aws-sdk-go/blob/a4592eaa6049d62c6eca32f3994eaa786e818dcd/models/apis/s3/2006-03-01/api-2.json#L3034-L3040

We'll work to get these model updated and included in the SDK's next release.

**Comment by meshuga** [comment] 2021-02-28 02:58
Thank you @jasdel ! I'm working on a project that uses most of the listing APIs, so will keep looking at similar issues.

**Comment by jasdel** [comment] 2021-03-03 18:17
A Smithy output shape only should decorate a member with [httpPayload](https://awslabs.github.io/smithy/1.0/spec/core/http-traits.html?highlight=httppayload#httppayload-trait)'s when the output shape it self does not describe the response. In this case without the `httpPayload` the SDK expected the GetBucketPolicy response body to contain an XML document containing a `<policy>` node. This is wrong for this operation, but is correct for an operation like [GetBucketAcl](https://docs.aws.amazon.com/AmazonS3/latest/API/API_GetBucketAcl.html) which does return an XML document.

`httpPayload` trait directs the how the SDK should deserialize the response body to a specific targeted field of the output type. This deserialization is driven by the type (aka shape) of the targeted field. In the case of `GetBucketPolicy`'s `Policy` member type is a `string` type. This means the deserializer should deserialize the entire response body as a string value.

The bug causing `GetBucketPolicy` not to decorate its `Policy` output member as the `httpPayload` was an missed customization in the process that converts the S3 API's raw model to a smithy model. We're working on fixing that upstream. This will allow the SDKs to consume this model correctly once the issue is fixed.

**Comment by jasdel** [comment] 2021-03-31 22:49
This has been fixed in the Amazon S3 API client's latest version. You'll be able to update to the latest version of the client, and the GetBucketPolicy operation should be working. Let us know if you have any additional issues, or feedback.

```sh
go get -d github.com/aws/aws-sdk-go-v2/service/s3@v1.3.0
```

**Closed by jasdel** 2021-03-31 22:49 UTC
Labels: bug
