### ISSUE TITLE
dynamodb@v1.25.1 compile failure

### ISSUE THREAD

**Issue by tendervittles** [aws/aws-sdk-go-v2#2408] opened 2023-12-05 01:03 UTC
### Describe the bug

I upgrading modules to latest and now dynamodb@1.25.1 fails.

```
../go/pkg/mod/github.com/aws/aws-sdk-go-v2/service/dynamodb@v1.25.1/api_op_BatchGetItem.go:259:32: cannot use &internalEndpointDiscovery.DiscoverEndpoint{…} (value of type *endpointdiscovery.DiscoverEndpoint) as "github.com/aws/smithy-go/middleware".SerializeMiddleware value in argument to stack.Serialize.Insert: *endpointdiscovery.DiscoverEndpoint does not implement "github.com/aws/smithy-go/middleware".SerializeMiddleware (missing method HandleSerialize)
../go/pkg/mod/github.com/aws/aws-sdk-go-v2/service/dynamodb@v1.25.1/api_op_BatchGetItem.go:266:33: cannot use c.fetchOpBatchGetItemDiscoverEndpoint (value of type func(ctx "context".Context, input interface{}, optFns ...func(*endpointdiscovery.DiscoverEndpointOptions)) (endpointdiscovery.WeightedAddress, error)) as func(ctx "context".Context, region string, options ...func(*endpointdiscovery.DiscoverEndpointOptions)) (endpointdiscovery.WeightedAddress, error) value in struct literal
../go/pkg/mod/github.com/aws/aws-sdk-go-v2/service/dynamodb@v1.25.1/api_op_BatchWriteItem.go:277:32: cannot use &internalEndpointDiscovery.DiscoverEndpoint{…} (value of type *endpointdiscovery.DiscoverEndpoint) as "github.com/aws/smithy-go/middleware".SerializeMiddleware value in argument to stack.Serialize.Insert: *endpointdiscovery.DiscoverEndpoint does not implement "github.com/aws/smithy-go/middleware".SerializeMiddleware (missing method HandleSerialize)
../go/pkg/mod/github.com/aws/aws-sdk-go-v2/service/dynamodb@v1.25.1/api_op_BatchWriteItem.go:284:33: cannot use c.fetchOpBatchWriteItemDiscoverEndpoint (value of type func(ctx "context".Context, input interface{}, optFns ...func(*endpointdiscovery.DiscoverEndpointOptions)) (endpointdiscovery.WeightedAddress, error)) as func(ctx "context".Context, region string, options ...func(*endpointdiscovery.DiscoverEndpointOptions)) (endpointdiscovery.WeightedAddress, error) value in struct literal
../go/pkg/mod/github.com/aws/aws-sdk-go-v2/service/dynamodb@v1.25.1/api_op_CreateBackup.go:164:32: cannot use &internalEndpointDiscovery.DiscoverEndpoint{…} (value of type *endpointdiscovery.DiscoverEndpoint) as "github.com/aws/smithy-go/middleware".SerializeMiddleware value in argument to stack.Serialize.Insert: *endpointdiscovery.DiscoverEndpoint does not implement "github.com/aws/smithy-go/middleware".SerializeMiddleware (missing method HandleSerialize)
../go/pkg/mod/github.com/aws/aws-sdk-go-v2/service/dynamodb@v1.25.1/api_op_CreateBackup.go:171:33: cannot use c.fetchOpCreateBackupDiscoverEndpoint (value of type func(ctx "context".Context, input interface{}, optFns ...func(*endpointdiscovery.DiscoverEndpointOptions)) (endpointdiscovery.WeightedAddress, error)) as func(ctx "context".Context, region string, options ...func(*endpointdiscovery.DiscoverEndpointOptions)) (endpointdiscovery.WeightedAddress, error) value in struct literal
../go/pkg/mod/github.com/aws/aws-sdk-go-v2/service/dynamodb@v1.25.1/api_op_CreateGlobalTable.go:183:32: cannot use &internalEndpointDiscovery.DiscoverEndpoint{…} (value of type *endpointdiscovery.DiscoverEndpoint) as "github.com/aws/smithy-go/middleware".SerializeMiddleware value in argument to stack.Serialize.Insert: *endpointdiscovery.DiscoverEndpoint does not implement "github.com/aws/smithy-go/middleware".SerializeMiddleware (missing method HandleSerialize)
../go/pkg/mod/github.com/aws/aws-sdk-go-v2/service/dynamodb@v1.25.1/api_op_CreateGlobalTable.go:190:33: cannot use c.fetchOpCreateGlobalTableDiscoverEndpoint (value of type func(ctx "context".Context, input interface{}, optFns ...func(*endpointdiscovery.DiscoverEndpointOptions)) (endpointdiscovery.WeightedAddress, error)) as func(ctx "context".Context, region string, options ...func(*endpointdiscovery.DiscoverEndpointOptions)) (endpointdiscovery.WeightedAddress, error) value in struct literal
../go/pkg/mod/github.com/aws/aws-sdk-go-v2/service/dynamodb@v1.25.1/api_op_CreateTable.go:284:32: cannot use &internalEndpointDiscovery.DiscoverEndpoint{…} (value of type *endpointdiscovery.DiscoverEndpoint) as "github.com/aws/smithy-go/middleware".SerializeMiddleware value in argument to stack.Serialize.Insert: *endpointdiscovery.DiscoverEndpoint does not implement "github.com/aws/smithy-go/middleware".SerializeMiddleware (missing method HandleSerialize)
../go/pkg/mod/github.com/aws/aws-sdk-go-v2/service/dynamodb@v1.25.1/api_op_CreateTable.go:291:33: cannot use c.fetchOpCreateTableDiscoverEndpoint (value of type func(ctx "context".Context, input interface{}, optFns ...func(*endpointdiscovery.DiscoverEndpointOptions)) (endpointdiscovery.WeightedAddress, error)) as func(ctx "context".Context, region string, options ...func(*endpointdiscovery.DiscoverEndpointOptions)) (endpointdiscovery.WeightedAddress, error) value in struct literal
../go/pkg/mod/github.com/aws/aws-sdk-go-v2/service/dynamodb@v1.25.1/api_op_CreateTable.go:284:32: too many errors (compile)
```

### Expected Behavior

Updated SDKv2 modules work together.

### Current Behavior

Not working together.

### Reproduction Steps

My go.mod contains:

      github.com/aws/smithy-go v1.18.1
      github.com/aws/aws-sdk-go-v2/service/dynamodb v1.25.1 // indirect

### AWS Go SDK V2 Module Versions Used

	github.com/aws/aws-lambda-go v1.41.0
	github.com/aws/aws-sdk-go-v2 v1.23.5
	github.com/aws/aws-sdk-go-v2/config v1.25.11
	github.com/aws/aws-sdk-go-v2/credentials v1.16.9
	github.com/aws/aws-sdk-go-v2/feature/rds/auth v1.3.8
	github.com/aws/aws-sdk-go-v2/service/cloudwatchlogs v1.29.2
	github.com/aws/aws-sdk-go-v2/service/ec2 v1.138.2
	github.com/aws/aws-sdk-go-v2/service/eks v1.35.2
	github.com/aws/aws-sdk-go-v2/service/iam v1.28.2
	github.com/aws/aws-sdk-go-v2/service/kms v1.27.2
	github.com/aws/aws-sdk-go-v2/service/lambda v1.49.2
	github.com/aws/aws-sdk-go-v2/service/rds v1.64.2
	github.com/aws/aws-sdk-go-v2/service/s3 v1.47.2
	github.com/aws/aws-sdk-go-v2/service/secretsmanager v1.25.2
	github.com/aws/aws-sdk-go-v2/service/ses v1.19.2
	github.com/aws/aws-sdk-go-v2/service/sns v1.26.2
	github.com/aws/aws-sdk-go-v2/service/sqs v1.29.2
	github.com/aws/aws-sdk-go-v2/service/sts v1.26.2
	github.com/aws/aws-sdk-go-v2/service/timestreamquery v1.20.3
	github.com/aws/aws-sdk-go-v2/service/timestreamwrite v1.23.3
	github.com/aws/smithy-go v1.18.1
	github.com/awslabs/aws-lambda-go-api-proxy v0.16.0
	go.opentelemetry.io/contrib/instrumentation/github.com/aws/aws-lambda-go/otellambda v0.46.1
	go.opentelemetry.io/contrib/instrumentation/github.com/aws/aws-lambda-go/otellambda/xrayconfig v0.46.1
	go.opentelemetry.io/contrib/instrumentation/github.com/aws/aws-sdk-go-v2/otelaws v0.46.1
	github.com/aws/aws-sdk-go-v2/aws/protocol/eventstream v1.5.3 // indirect
	github.com/aws/aws-sdk-go-v2/feature/ec2/imds v1.14.9 // indirect
	github.com/aws/aws-sdk-go-v2/internal/configsources v1.2.8 // indirect
	github.com/aws/aws-sdk-go-v2/internal/endpoints/v2 v2.5.8 // indirect
	github.com/aws/aws-sdk-go-v2/internal/ini v1.7.1 // indirect
	github.com/aws/aws-sdk-go-v2/internal/v4a v1.2.8 // indirect
	github.com/aws/aws-sdk-go-v2/service/dynamodb v1.25.1 // indirect
	github.com/aws/aws-sdk-go-v2/service/internal/accept-encoding v1.10.3 // indirect
	github.com/aws/aws-sdk-go-v2/service/internal/checksum v1.2.8 // indirect
	github.com/aws/aws-sdk-go-v2/service/internal/endpoint-discovery v1.8.9 // indirect
	github.com/aws/aws-sdk-go-v2/service/internal/presigned-url v1.10.8 // indirect
	github.com/aws/aws-sdk-go-v2/service/internal/s3shared v1.16.8 // indirect
	github.com/aws/aws-sdk-go-v2/service/sso v1.18.2 // indirect
	github.com/aws/aws-sdk-go-v2/service/ssooidc v1.21.2 // indirect

### Compiler and Version used

go version go1.21.4 linux/amd64

### Operating System and version

Linux dev 6.2.0-37-generic #38~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Nov  2 18:01:13 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

**Comment by lucix-aws** [comment] 2023-12-05 02:06
Duplicate of #2401, please update all of your sdk v2 modules and ensure they're at the latest versions.

**Closed by lucix-aws** 2023-12-05 02:06 UTC
Labels: bug, needs-triage
