### ISSUE TITLE
Location service doesn't load the aws region in request

### ISSUE THREAD

**Issue by hsequeda** [aws/aws-sdk-go-v2#1325] opened 2021-06-30 21:23 UTC
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [API reference](https://docs.aws.amazon.com/sdk-for-go/v2/api/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-go-v2/issues) and didn't find any solution
  
**Describe the bug**
https://gist.github.com/hsequeda/4c9ace9c0e76cbabd9b9e8312624662f
When I try to run this test the location service throw me this: 
`--- FAIL: TestCreateRoute (1.89s)
    aws_location_map_service_test.go:32:
        	Error Trace:	aws_location_map_service_test.go:32
        	Error:      	Received unexpected error:
        	            	operation error Location: SearchPlaceIndexForText, failed to resolve service endpoint, an AWS region is required, but was not found
        	Test:       	TestCreateRoute
FAIL`

To verify if the credentials are fine, the code contains an invocation of the list buckets method of s3 and works fine with the same 'configs'.

**Version of AWS SDK for Go?**
v1.3.0

**Version of Go (`1.16`)?**

**Comment by KaibaLopez** [comment] 2021-07-15 20:40
Hi @hsequeda ,
thanks for bringing this up to us, we'll start investigating on the issue.

**Comment by skmcgrail** [comment] 2021-07-16 22:26
Was able to confirm this behavior. From some brief debugging it appears the client region is not getting set on the context within the stack. Still investigating the root cause.

**Comment by skmcgrail** [comment] 2021-07-16 22:30
It appears that there is a bug in code generation which result in the `RegisterServiceMetadata` middleware not being added to the stack for any of the `location` service operations.

**Comment by skmcgrail** [comment] 2021-07-16 23:09
Looks like this bug is affects the following API clients:
```
service/amp
service/location
service/snowdevicemanagement
```

**Comment by skmcgrail** [comment] 2021-07-19 16:43
Related: https://github.com/aws/aws-sdk-go-v2/issues/1325

**Comment by skmcgrail** [comment] 2021-07-19 18:21
Re-opning this until we cut a new release with the merged fix.

**Comment by Skarlso** [comment] 2021-08-25 12:27
Hi! Same observation can be made for the marketplacemetering service.

**Comment by skmcgrail** [comment] 2021-12-13 22:04
This particular issue was resolved in https://github.com/aws/aws-sdk-go-v2/releases/tag/release-2021-08-04 but was not closed in a timely manner.

@Skarlso if you are still having issues with the AWS Marketplace Metering service please cut us a new issue describing the issue, and provide a code sample for reproducing the error you are seeing. From a quick glace this service does not have the root cause issue here.

**Closed by skmcgrail** 2021-12-13 22:04 UTC
Labels: bug
