### ISSUE TITLE
Interfaces For Testing

### ISSUE THREAD

**Issue by rossedman** [aws/aws-sdk-go-v2#808] opened 2020-10-09 16:08 UTC
**Is your feature request related to a problem? Please describe.**
It is very hard to wrap and abstract away this SDK without interfaces. Having interfaces of any kind would help generate mocks or atleast make testing easier in an application that consumed this SDK. Right now testing is very hard with this SDK in your codebase.

**Describe the solution you'd like**
Interfaces for the providers of some sort that can be used when testing.

**Describe alternatives you've considered**
Tracking down all the methods I'm using, writing interfaces and generating mocks from those but seems like the wrong place to be.

**Additional context**

**Comment by diogomatsubara** [comment] 2020-10-09 16:14
@rossedman See https://github.com/aws/aws-sdk-go-v2/issues/70, I think this is a duplicate of that one.

**Comment by skmcgrail** [comment] 2020-10-09 22:13
Let's consolidate the discussion to https://github.com/aws/aws-sdk-go-v2/issues/786 which is a duplicate issue that covers the topic of mocking client in SDK versions at or after `v0.25.0`.

**Closed by skmcgrail** 2020-10-09 22:13 UTC
Labels: feature-request
