### ISSUE TITLE
Customer issue: STS Assume Role signature mismatch

### ISSUE THREAD

**Issue by skotambkar** [aws/aws-sdk-go-v2#914] opened 2020-11-19 02:48 UTC
Customer reported signature mismatch error when assuming role via STS, need to investigate the same.

Customer issue: https://github.com/aws/aws-sdk-go-v2/issues/883#issuecomment-727609275

Reproducible code as provided by customer: https://github.com/aws/aws-sdk-go-v2/issues/883#issuecomment-728435274

**Comment by gmauleon** [comment] 2020-12-07 16:48
Just for information, I got the same problem with `v0.30.0`

**Comment by jasdel** [comment] 2020-12-14 19:09
@gmauleon are you consistently running into this issue or is it periodically occurring?

**Comment by gmauleon** [comment] 2020-12-14 19:34
Consistent on my side. I shelved it and planned to use v1 for the time being but could certainly retry it this week if you need more informations.

**Comment by jasdel** [comment] 2020-12-15 01:16
Thanks for the update @gmauleon. I'm trying to reproduce this issue, but not able to with latest release version v0.30.0, and HEAD of the v2 SDK repo.

```go
package main

import (
	"context"
	"fmt"
	"log"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/config"
	"github.com/aws/aws-sdk-go-v2/credentials/stscreds"
	"github.com/aws/aws-sdk-go-v2/service/sts"
)

func main() {
	if err := do(); err != nil {
		log.Fatal(err)
	}
}

func do() error {
	cfg, err := config.LoadDefaultConfig(
		config.WithRegion("us-west-2"),
		config.WithClientLogMode(aws.LogSigning),
	)
	if err != nil {
		return err
	}

	stsclient := sts.NewFromConfig(cfg)

	role := fmt.Sprintf("arn:aws:iam::%s:role/%s", accountID, roleName)
	provider := stscreds.NewAssumeRoleProvider(stsclient, role)

	// SDK tip:
	cfg.Credentials = aws.NewCredentialsCache(provider)
	// SDK v0.30.0
	cfg.Credentials = &aws.CredentialsCache{Provider: provider}

	creds, err := cfg.Credentials.Retrieve(context.Background())
	if err != nil {
		return fmt.Errorf("failed to get credentials, %w", err)
	}

	log.Println("Credentials ", creds.AccessKeyID, creds.Source)

	return nil
}
```

I'm using the following sample code to reproduce this issue. If you have a sample that is able to reproduce this problem that would be very helpful to investigate this issue.

```sh
# Update to the tip of the smithy-go currently, `511e8c85` 
go get github.com/awslabs/smithy-go@ac098bf4

# Update to the tip of the SDK currently, `511e8c85`
go get github.com/aws/aws-sdk-go-v2@511e8c85
go get github.com/aws/aws-sdk-go-v2/service/sts@511e8c85
go get github.com/aws/aws-sdk-go-v2/credentials@511e8c85
go get github.com/aws/aws-sdk-go-v2/config@511e8c85
```

**Comment by jasdel** [comment] 2020-12-18 20:08
The only way I've been able to reproduce this is when the original `LoadDefaultConfig` is unable to retrieve credentials to do the assume role with. Could you looking if the `cfg.Credentials` value is a [aws.AnonymousCredentials](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/aws/#AnonymousCredentials), or `nil`?

**Comment by gmauleon** [comment] 2020-12-18 22:36
Thanks a lot for looking into this, I'll be out and will not be able to 
look at it until most likely January, sorry about that :(

I'll see if I can look at my code next week but no promises.

Have some happy holidays Jason!

**Comment by Chandrian** [comment] 2021-01-05 21:44
Using v0.4, I'm getting the same issue `operation error Organizations: ListAccountsForParent, failed to sign request: failed to retrieve credentials: operation error STS: AssumeRole, https response error StatusCode: 403, RequestID: ..., api error SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.`
if I use:
`ctx := context.TODO()
	cfg, err := config.LoadDefaultConfig(ctx,
		config.WithRegion("us-east-1"),
		//config.WithClientLogMode(aws.LogSigning),
	)
	if err != nil {
		log.Fatal(err)
	}

	stsclient := sts.NewFromConfig(cfg)

	provider := stscreds.NewAssumeRoleProvider(stsclient, *assumeRole.masterARN)

	// SDK tip:
	cfg.Credentials = aws.NewCredentialsCache(provider)`
And then directly try to use it:
`	orgClient := organizations.NewFromConfig(cfg)
listAccountsForParentInput := &organizations.ListAccountsForParentInput{
		ParentId: aws.String(ou),
	}
	p := organizations.NewListAccountsForParentPaginator(orgClient, listAccountsForParentInput)
	var emails []string
	for p.HasMorePages() {
		listAccountsForParentOutput, err := p.NextPage(context.Background())
		if err != nil {
			log.Panicf("failed to get the page for accounts in assume OU: %v", err)
		}
		for _, account := range listAccountsForParentOutput.Accounts {
			emails = append(emails, *account.Email)
		}
	}`
But if in between I add the following, everything works fine.... Any idea why?
`creds, err := cfg.Credentials.Retrieve(context.Background())
	if err != nil {
		log.Fatal(err)
	}`

**Comment by jasdel** [comment] 2021-01-05 22:20
Thanks for the update, @Chandrian could you clarify the version of the V2 SDK that you are using. We recently released v0.31.0 as an release candidate of the v2 SDK.

We've been investigating this issue, but have yet been able to reproduce this issue. When the `config.WithClientLogMode(aws.LogSigning)` is enabled, do you see the `ListAccountsForParent` operation call being signed?  In addition, could you `aws.LogRequest` and `aws.LogResponseWithBody` as well, and ensure that credentials are being retrieved from the STS AssumeRole operation call.

When you run into this issue does it happen every time, or periodically?  and when you manually call `cfg.Credentials.Retrieve` does the problem never occur again?

**Comment by Chandrian** [comment] 2021-01-05 22:39
Yes, without the retrieve it does happen 100% of the time. with the retrieve, it never happens

**Comment by jasdel** [comment] 2021-01-05 22:56
Looks like the issue causing the signature to be invalid is that something is preventing the SDK from computing the `sha256` of the request body. Since its not computing the body, the sha256 of empty string is being used instead `e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855`

**Comment by jasdel** [comment] 2021-01-05 23:26
The issue is occurring because the SDK is effectively polluting of the `Context` value passed down from the top level operation -> signer -> credentials retrieve -> assume role. In my above code example this is the reason the content sha256 of an empty string value was being used with the STS request. S3's ListBuckets operation call has not body, i.e. empty string. This same issue would be similar for any nested API call invoked within the chain of another operation's middleware stack. Basically we'll need to "clear/blank" a set of context values that must not be passed down to nested operation calls within a middleware stack. `content-sha256` being the example in this case.

We're working on a fix for this bug, and will update this issue when a fix is available.

---

With that said the following is a workaround that will ensure the content-sha256 value will be cleared for nested operations like the STS assume role.

Custom middleware that clears the content-shaw256 context value.
```go
type clearContextContentSha256 struct{}

func (clearContextContentSha256) ID() string {
	return "clear content-sha256 workaround"
}

func (clearContextContentSha256) HandleInitialize(
	ctx context.Context, in middleware.InitializeInput, next middleware.InitializeHandler) (
	out middleware.InitializeOutput, metadata middleware.Metadata, err error,
) {
	ctx = v4.SetPayloadHash(ctx, "")
	return next.HandleInitialize(ctx, in)
}
```

This is then used when loading the config to ensure all operations don't pollute nested operation calls.
```go
cfg, err := config.LoadDefaultConfig(ctx,
	config.WithRegion("us-west-2"),
	config.WithClientLogMode(aws.LogSigning|aws.LogRequestWithBody|aws.LogResponseWithBody),
	config.WithAPIOptions([]func(stack *middleware.Stack) error{
		func(stack *middleware.Stack) error {
			return stack.Initialize.Add(clearContextContentSha256{}, middleware.Before)
		},
	}),
)
if err != nil {
	return fmt.Errorf("failed to load config, %w", err)
}
```

**Comment by Chandrian** [comment] 2021-01-05 23:38
I tried the workaround and it is working! Thank you for the quick turn around on this!

**Closed** 2021-01-08 20:16 UTC
Labels: bug
