### ISSUE TITLE
location service: dial tcp: lookup geo.us-east-1.amazonaws.com: no such host

### ISSUE THREAD

**Issue by jaanauati** [aws/aws-sdk-go-v2#1506] opened 2021-11-19 17:06 UTC
### Documentation

- [X] I've gone though the [API reference](https://docs.aws.amazon.com/sdk-for-go/v2/api/)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-go-v2/issues) and didn't find any solution

### Describe the bug

Looks like the geo endpoints are wrongly configured to point to `geo.{region}.amazonws.com`, which leads to the following error:

```
operation error Location: DescribePlaceIndex, exceeded maximum number of attempts, 3, https response error StatusCode: 0, RequestID: , request send failed, Get "https://geo.us-east-1.amazonaws.com/places/v0/indexes/my-place-index": dial tcp: lookup geo.us-east-1.amazonaws.com: no such host
```

After spending some time poking with aws cli (using `--debug` flag) I found that the actual endpoint for this case should be:
https://places.geo.us-east-1.amazonaws.com (or maps.geo.{region}.amazonaws.com for the case of maps).

https://github.com/aws/aws-sdk-go-v2/blob/main/service/location/internal/endpoints/endpoints.go#L130

Btw, In case that someone else runs into this same issue, I'm currently using the following workaround, which seems to work well:
```
	configureUrlResolver := func(options *location.Options) {
		resolver := location.EndpointResolverFromURL("https://places.geo.us-east-1.amazonaws.com")
		options.EndpointResolver = resolver
	}
	location_client := location.NewFromConfig(cfg, configureUrlResolver)
```

### Expected behavior

CreatePlaceIndexInput, DescribePlaceIndex, UpdatePlaceIndexInput, and DeletePlaceIndex functions should be able to create, describe, update and delete place index resources.

### Current behavior

CreatePlaceIndexInput, DescribePlaceIndex, UpdatePlaceIndexInput, and DeletePlaceIndex functions return the following error:

```
operation error Location: DescribePlaceIndex, exceeded maximum number of attempts, 3, https response error StatusCode: 0, RequestID: , request send failed, Get "https://geo.us-east-1.amazonaws.com/places/v0/indexes/my-place-index": dial tcp: lookup geo.us-east-1.amazonaws.com: no such host

```

### Steps to Reproduce

```
	ctx := context.TODO()
	cfg, err := config.LoadDefaultConfig(ctx)
	if err != nil {
		log.Fatal(err)
		return err
	}
	location_client := location.NewFromConfig(cfg)
        indexName := "my-awesome-index"
	details, err := location_client.DescribePlaceIndex(ctx, &location.DescribePlaceIndexInput{IndexName: &indexName})

```

### Possible Solution

maybe including some additional endpoints or adding support for an additional param like: `"{resourceType}."geo.{region}.amazonaws.com"`

https://github.com/aws/aws-sdk-go-v2/blob/main/service/location/internal/endpoints/endpoints.go#L130

### AWS Go SDK version used

v1.11.0 

### Compiler and Version used

go version go1.16.3 darwin/amd64

### Operating System and version

macos 11.4

**Comment by skmcgrail** [comment] 2021-11-22 17:20
Thanks for raising this issue @jaanauati, this appears to be a code-generation bug in our operation serializer. The host prefixes like `places.`, `tracking.`, etc. are to be sourced from the [model](https://github.com/aws/aws-sdk-go-v2/blob/main/codegen/sdk-codegen/aws-models/location.2020-11-19.json#L2232) to augment the resolved endpoint. We will need to investigate why our current code-generation logic is not handling this correctly.

**Comment by karl-dau** [comment] 2021-11-25 15:46
I am facing the same problem, but can't get the workaround to work:

`
cfg, err := config.LoadDefaultConfig(context.Background())
	if err != nil {
		panic(err)
	}
	configureUrlResolver := func(options *location.Options) {
		options.EndpointResolver = location.EndpointResolverFromURL("https://tracking.geo.eu-central-1.amazonaws.com")
	}
	locserv := location.NewFromConfig(cfg, configureUrlResolver)
	trackerName := "MyFirstTracker"
	out, err := locserv.DescribeTracker(context.TODO(), &location.DescribeTrackerInput{
		TrackerName: &trackerName,
	})
	if err != nil {
		panic(err)
	}`

Panics with:

`operation error Location: DescribeTracker, https response error StatusCode: 403, RequestID: <redacted>, api error MissingAuthenticationTokenException: Missing Authentication Token`

Credentials seems fine (aws cli location works) and I wrote a basic Python program that does the same using boto3 and it works fine.

**Comment by jaanauati** [comment] 2021-11-25 15:57
Hi., yes , i did face that same error w the describe-place operation, I
made this fix:
https://github.com/aws/aws-sdk-go-v2/pull/1500, the rest of the operations
seem to work well for me.

**Comment by skmcgrail** [comment] 2021-12-02 21:28
I have a root cause for this and have a fix that should make it into our next release. Appreciate this bug report, as this issue impacted a few other service clients. Additionally the root cause was also applicable in another situation with idempotency token auto-fill behavior for some service clients.

**Comment by skmcgrail** [comment] 2021-12-02 22:49
The missing SigV4 signing middleware is missing due to a modeling issue that we will work with the service team to get corrected. Until then I have put in a customization that will ensure that the signing middleware is attached to fix that issue.

It looks like that issue in particular is limited to just 6 of the service's operations.

**Comment by jaanauati** [comment] 2021-12-02 22:56
@skmcgrail thank you!, regarding the signature issues please see https://github.com/aws/aws-sdk-go-v2/pull/1500.

**Comment by skmcgrail** [comment] 2021-12-03 01:02
Holding this issue open until our next tagged release, but the fix is now merged into main.

**Comment by skmcgrail** [comment] 2021-12-06 20:42
Closing this issue, as the changes have been [released](https://github.com/aws/aws-sdk-go-v2/releases/tag/release-2021-12-03). You should be able to `go get github.com/aws/aws-sdk-go-v2/service/location@v1.9.2` to resolve this issue.

**Closed by skmcgrail** 2021-12-06 20:42 UTC
Labels: bug
