### ISSUE TITLE
HandleDeserialize Error from MiddleWare

### ISSUE THREAD

**Issue by sathishdv** [aws/aws-sdk-go-v2#2924] opened 2024-12-06 18:40 UTC
### Describe the bug

while running a high load dealing with DynamoDB with Provisioned Capacity started getting these errors 
```
"github.com/aws/smithy-go/transport/http.(*errorCloseResponseBodyMiddleware).HandleDeserialize(0x41d445?, {0x1d3e698?, 0xc000535d40?}, {{0x170bfa0?, 0xc000535830?}}, {0x1d2e760?, 0xc0054577c0?})" pod=pod_name time=2024-12-06T18:28:49.581311541Z
log="	/build/vendor/github.com/aws/aws-sdk-go-v2/aws/transport/http/response_error_middleware.go:31 +0x53 fp=0xc00288e588 sp=0xc00288e4e0 pc=0xd82093" pod=pod_name time=2024-12-06T18:28:49.581294711Z
```
This error causing pods to crash and continous restarts.

SDK Version: v1.32.6 

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

This error should not happen, if not atleast these should be error type and retryable

### Current Behavior

This error is not handled properly and causing crashes

### Reproduction Steps

Can see this consistently on high load. Espcially after auto-scaled up on Provisioned capacity. In the event of provisionedExceeded error, we retry until the operation succeeds. 

### SDK version used

 v1.32.6 

### Environment details (Version of Go (`go version`)? OS name and version, etc.)

 v1.32.6

**Comment by RanVaknin** [comment] 2024-12-06 21:27
Hi @sathishdv ,

My guess is that the behaves unexpectedly under high load and causes a panic in that middleware. Perhaps a connection that is closed prematurely. 

Can you please enable the SDK wire logs, and see if you can capture the logs before the panic? 

```go
	cfg, err := config.LoadDefaultConfig(context.TODO(), config.WithRegion("us-east-1"), config.WithClientLogMode(aws.LogRequest|aws.LogResponseWithBody))
```

Thanks,
Ran~

**Comment by sathishdv** [comment] 2024-12-07 04:11
Hi @RanVaknin Thanks for the response. Yes, the connection seems to be closed prematurely. I can see the error propagated and logs this error 

```
deserialization failed, failed to decode response body, read tcp <<ip_address>>:42570-><<ip_address>>:443: use of closed network connection
```

Is it ok to retry such errors? I believe connection getting closed abruptly, prolly retry should should resolve, but the problem is SDK doesn't provide any nicer way to handle these kind of errors/exceptions. I have to check the strings.Contain for any of the keywords 😊

**Comment by sathishdv** [comment] 2024-12-10 04:04
Hi @RanVaknin in fact the above error when retried the operation resulting in context cancelled. Looks like it is unable to establish connection, so pods getting restarted and the AWS Config initializes and then works.

**Comment by RanVaknin** [comment] 2024-12-12 21:04
Hi @sathishdv ,

This is related to https://github.com/aws/aws-sdk-go-v2/issues/2737

Currently in our backlog to investigate. We also got your internal support ticket.

I'm going to close this as duplicate and ask you to check the other ticket for further updates on the matter.

Thanks again,
Ran~

**Closed** 2024-12-12 21:04 UTC
Labels: bug, p2

**Comment by sathishdv** [comment] 2024-12-13 17:30
Hi @RanVaknin thanks for the update.

**Comment by eliebleton-manomano** [comment] 2024-12-31 13:14
I'm observing panics down stack from `HandleDeserialize` when calling `s3.ListObjectV2` with about ~15 concurrent calls. All is well without concurrency. This issue was closed as a duplicate of DynamoDB specific issue - just wanted to chime in and point out it could be endpoint agnostic.
