### ISSUE TITLE
ddb.WaitUntilTableExists never completes

### ISSUE THREAD

**Issue by slaskis** [aws/aws-sdk-go-v2#146] opened 2018-03-08 10:59 UTC
Please fill out the sections below to help us address your issue.

### Version of AWS SDK for Go?
`aws-sdk-go/2.0.0-preview.2`

### Version of Go (`go version`)?
`go version go1.10 darwin/amd64`

### What issue did you see?
I'm creating a dynamodb table and then want to wait for it to be active before continuing. 

the waiting it polling the describe table and after two attempts it is `ACTIVE` but it doesn't stop trying until it times out. 

### Steps to reproduce

Here's a test function:

```
func TestWaiter(t *testing.T) {
	cfg, _ := external.LoadDefaultAWSConfig()
	cfg.Credentials = aws.NewStaticCredentialsProvider(acc, sec, "")
	cfg.LogLevel = aws.LogDebugWithHTTPBody
	ddb := dynamodb.New(cfg)
	req := ddb.CreateTableRequest(&dynamodb.CreateTableInput{
		TableName: aws.String(tableName),
		KeySchema: []dynamodb.KeySchemaElement{
			{
				AttributeName: aws.String("number"),
				KeyType:       dynamodb.KeyTypeHash,
			},
		},
		AttributeDefinitions: []dynamodb.AttributeDefinition{
			{
				AttributeName: aws.String("number"),
				AttributeType: dynamodb.ScalarAttributeTypeS,
			},
		},
		ProvisionedThroughput: &dynamodb.ProvisionedThroughput{
			ReadCapacityUnits:  aws.Int64(1),
			WriteCapacityUnits: aws.Int64(1),
		},
	})
	_, err := req.Send()
	if err != nil {
		t.Fatal(err)
	}

	// using WithContext so we can make it fail faster
	err = ddb.WaitUntilTableExistsWithContext(context.Background(), &dynamodb.DescribeTableInput{
		TableName: aws.String(tableName),
	}, aws.WithWaiterDelay(aws.ConstantWaiterDelay(3*time.Second)),
		aws.WithWaiterMaxAttempts(10))
	if err != nil {
		t.Fatal(err)
	}
}
```

Response table status (from the logs):

- CREATING
- CREATING
- CREATING
- ACTIVE
- ACTIVE
- ACTIVE
- ACTIVE
- ACTIVE
- ACTIVE
- ACTIVE
- ACTIVE
- `ResourceNotReady: exceeded wait attempts`

<details>
 <summary>Full Logs</summary>

```
Running tool: /usr/local/bin/go test -timeout 120s numbers -run ^TestWaiter$

2018/03/08 11:51:31 DEBUG: Request dynamodb/CreateTable Details:
---[ REQUEST POST-SIGN ]-----------------------------
POST / HTTP/1.1
Host: dynamodb.eu-central-1.amazonaws.com
User-Agent: aws-sdk-go/2.0.0-preview.2 (go1.10; darwin; amd64)
Content-Length: 236
Accept-Encoding: identity
Authorization: AWS4-HMAC-SHA256 Credential=<redacted>/20180308/eu-central-1/dynamodb/aws4_request, SignedHeaders=accept-encoding;content-length;content-type;host;x-amz-date;x-amz-target, Signature=a67e1ba529fe578726b48ce0f0077968c77598017bd09a8a739bd2d342e0743a
Content-Type: application/x-amz-json-1.0
X-Amz-Date: 20180308T105131Z
X-Amz-Target: DynamoDB_20120810.CreateTable

{"AttributeDefinitions":[{"AttributeName":"number","AttributeType":"S"}],"KeySchema":[{"AttributeName":"number","KeyType":"HASH"}],"ProvisionedThroughput":{"ReadCapacityUnits":1,"WriteCapacityUnits":1},"TableName":"numbers-test-waiter"}
-----------------------------------------------------
2018/03/08 11:51:32 DEBUG: Response dynamodb/CreateTable Details:
---[ RESPONSE ]--------------------------------------
HTTP/1.1 200 OK
Content-Length: 509
Connection: keep-alive
Content-Type: application/x-amz-json-1.0
Date: Thu, 08 Mar 2018 10:51:32 GMT
Server: Server
X-Amz-Crc32: 3893517150
X-Amzn-Requestid: TTE3NU0GJBEC46J2AEE7TN11U7VV4KQNSO5AEMVJF66Q9ASUAAJG


-----------------------------------------------------
2018/03/08 11:51:32 {"TableDescription":{"AttributeDefinitions":[{"AttributeName":"number","AttributeType":"S"}],"CreationDateTime":1.520506292272E9,"ItemCount":0,"KeySchema":[{"AttributeName":"number","KeyType":"HASH"}],"ProvisionedThroughput":{"NumberOfDecreasesToday":0,"ReadCapacityUnits":1,"WriteCapacityUnits":1},"TableArn":"arn:aws:dynamodb:eu-central-1:<redacted>:table/numbers-test-waiter","TableId":"e319b9c0-0dd0-4777-bf12-4e3a210e41ed","TableName":"numbers-test-waiter","TableSizeBytes":0,"TableStatus":"CREATING"}}
2018/03/08 11:51:32 DEBUG: Request dynamodb/DescribeTable Details:
---[ REQUEST POST-SIGN ]-----------------------------
POST / HTTP/1.1
Host: dynamodb.eu-central-1.amazonaws.com
User-Agent: aws-sdk-go/2.0.0-preview.2 (go1.10; darwin; amd64) Waiter
Content-Length: 35
Accept-Encoding: identity
Authorization: AWS4-HMAC-SHA256 Credential=<redacted>/20180308/eu-central-1/dynamodb/aws4_request, SignedHeaders=accept-encoding;content-length;content-type;host;x-amz-date;x-amz-target, Signature=418171e38c3b1a32d8d6f48f99754e37459de2c2c23797a20f0e81ca224ed7cd
Content-Type: application/x-amz-json-1.0
X-Amz-Date: 20180308T105132Z
X-Amz-Target: DynamoDB_20120810.DescribeTable

{"TableName":"numbers-test-waiter"}
-----------------------------------------------------
2018/03/08 11:51:32 DEBUG: Response dynamodb/DescribeTable Details:
---[ RESPONSE ]--------------------------------------
HTTP/1.1 200 OK
Content-Length: 498
Connection: keep-alive
Content-Type: application/x-amz-json-1.0
Date: Thu, 08 Mar 2018 10:51:32 GMT
Server: Server
X-Amz-Crc32: 2964354032
X-Amzn-Requestid: B826GH75ADTCM03BKFM4R1V2QJVV4KQNSO5AEMVJF66Q9ASUAAJG


-----------------------------------------------------
2018/03/08 11:51:32 {"Table":{"AttributeDefinitions":[{"AttributeName":"number","AttributeType":"S"}],"CreationDateTime":1.520506292272E9,"ItemCount":0,"KeySchema":[{"AttributeName":"number","KeyType":"HASH"}],"ProvisionedThroughput":{"NumberOfDecreasesToday":0,"ReadCapacityUnits":1,"WriteCapacityUnits":1},"TableArn":"arn:aws:dynamodb:eu-central-1:<redacted>:table/numbers-test-waiter","TableId":"e319b9c0-0dd0-4777-bf12-4e3a210e41ed","TableName":"numbers-test-waiter","TableSizeBytes":0,"TableStatus":"CREATING"}}
2018/03/08 11:51:35 DEBUG: Request dynamodb/DescribeTable Details:
---[ REQUEST POST-SIGN ]-----------------------------
POST / HTTP/1.1
Host: dynamodb.eu-central-1.amazonaws.com
User-Agent: aws-sdk-go/2.0.0-preview.2 (go1.10; darwin; amd64) Waiter
Content-Length: 35
Accept-Encoding: identity
Authorization: AWS4-HMAC-SHA256 Credential=<redacted>/20180308/eu-central-1/dynamodb/aws4_request, SignedHeaders=accept-encoding;content-length;content-type;host;x-amz-date;x-amz-target, Signature=b9e9e31d4995c827b7452f47703b730a738331247842dc4a8556a3bd181c47af
Content-Type: application/x-amz-json-1.0
X-Amz-Date: 20180308T105135Z
X-Amz-Target: DynamoDB_20120810.DescribeTable

{"TableName":"numbers-test-waiter"}
-----------------------------------------------------
2018/03/08 11:51:35 DEBUG: Response dynamodb/DescribeTable Details:
---[ RESPONSE ]--------------------------------------
HTTP/1.1 200 OK
Content-Length: 498
Connection: keep-alive
Content-Type: application/x-amz-json-1.0
Date: Thu, 08 Mar 2018 10:51:35 GMT
Server: Server
X-Amz-Crc32: 2964354032
X-Amzn-Requestid: IDA0KMLF3P4VNSJVLOKQJOEQTFVV4KQNSO5AEMVJF66Q9ASUAAJG


-----------------------------------------------------
2018/03/08 11:51:35 {"Table":{"AttributeDefinitions":[{"AttributeName":"number","AttributeType":"S"}],"CreationDateTime":1.520506292272E9,"ItemCount":0,"KeySchema":[{"AttributeName":"number","KeyType":"HASH"}],"ProvisionedThroughput":{"NumberOfDecreasesToday":0,"ReadCapacityUnits":1,"WriteCapacityUnits":1},"TableArn":"arn:aws:dynamodb:eu-central-1:<redacted>:table/numbers-test-waiter","TableId":"e319b9c0-0dd0-4777-bf12-4e3a210e41ed","TableName":"numbers-test-waiter","TableSizeBytes":0,"TableStatus":"CREATING"}}
2018/03/08 11:51:38 DEBUG: Request dynamodb/DescribeTable Details:
---[ REQUEST POST-SIGN ]-----------------------------
POST / HTTP/1.1
Host: dynamodb.eu-central-1.amazonaws.com
User-Agent: aws-sdk-go/2.0.0-preview.2 (go1.10; darwin; amd64) Waiter
Content-Length: 35
Accept-Encoding: identity
Authorization: AWS4-HMAC-SHA256 Credential=<redacted>/20180308/eu-central-1/dynamodb/aws4_request, SignedHeaders=accept-encoding;content-length;content-type;host;x-amz-date;x-amz-target, Signature=409b6a9a864e6ece68fb53fa15c624d3c363601b0bb3018953d380a4ce539ad3
Content-Type: application/x-amz-json-1.0
X-Amz-Date: 20180308T105138Z
X-Amz-Target: DynamoDB_20120810.DescribeTable

{"TableName":"numbers-test-waiter"}
-----------------------------------------------------
2018/03/08 11:51:38 DEBUG: Response dynamodb/DescribeTable Details:
---[ RESPONSE ]--------------------------------------
HTTP/1.1 200 OK
Content-Length: 496
Connection: keep-alive
Content-Type: application/x-amz-json-1.0
Date: Thu, 08 Mar 2018 10:51:38 GMT
Server: Server
X-Amz-Crc32: 570748969
X-Amzn-Requestid: NBSIF313LBKK2PRAVVRGU169HJVV4KQNSO5AEMVJF66Q9ASUAAJG


-----------------------------------------------------
2018/03/08 11:51:38 {"Table":{"AttributeDefinitions":[{"AttributeName":"number","AttributeType":"S"}],"CreationDateTime":1.520506292272E9,"ItemCount":0,"KeySchema":[{"AttributeName":"number","KeyType":"HASH"}],"ProvisionedThroughput":{"NumberOfDecreasesToday":0,"ReadCapacityUnits":1,"WriteCapacityUnits":1},"TableArn":"arn:aws:dynamodb:eu-central-1:<redacted>:table/numbers-test-waiter","TableId":"e319b9c0-0dd0-4777-bf12-4e3a210e41ed","TableName":"numbers-test-waiter","TableSizeBytes":0,"TableStatus":"ACTIVE"}}
2018/03/08 11:51:41 DEBUG: Request dynamodb/DescribeTable Details:
---[ REQUEST POST-SIGN ]-----------------------------
POST / HTTP/1.1
Host: dynamodb.eu-central-1.amazonaws.com
User-Agent: aws-sdk-go/2.0.0-preview.2 (go1.10; darwin; amd64) Waiter
Content-Length: 35
Accept-Encoding: identity
Authorization: AWS4-HMAC-SHA256 Credential=<redacted>/20180308/eu-central-1/dynamodb/aws4_request, SignedHeaders=accept-encoding;content-length;content-type;host;x-amz-date;x-amz-target, Signature=e51a50d643411426d0e8d5dca043c3c6f98c9ffa06bc4e1f5b95b5ae053d7800
Content-Type: application/x-amz-json-1.0
X-Amz-Date: 20180308T105141Z
X-Amz-Target: DynamoDB_20120810.DescribeTable

{"TableName":"numbers-test-waiter"}
-----------------------------------------------------
2018/03/08 11:51:41 DEBUG: Response dynamodb/DescribeTable Details:
---[ RESPONSE ]--------------------------------------
HTTP/1.1 200 OK
Content-Length: 496
Connection: keep-alive
Content-Type: application/x-amz-json-1.0
Date: Thu, 08 Mar 2018 10:51:41 GMT
Server: Server
X-Amz-Crc32: 570748969
X-Amzn-Requestid: 5PC66KSCRLT7MNSRFOK9QR04MVVV4KQNSO5AEMVJF66Q9ASUAAJG


-----------------------------------------------------
2018/03/08 11:51:41 {"Table":{"AttributeDefinitions":[{"AttributeName":"number","AttributeType":"S"}],"CreationDateTime":1.520506292272E9,"ItemCount":0,"KeySchema":[{"AttributeName":"number","KeyType":"HASH"}],"ProvisionedThroughput":{"NumberOfDecreasesToday":0,"ReadCapacityUnits":1,"WriteCapacityUnits":1},"TableArn":"arn:aws:dynamodb:eu-central-1:<redacted>:table/numbers-test-waiter","TableId":"e319b9c0-0dd0-4777-bf12-4e3a210e41ed","TableName":"numbers-test-waiter","TableSizeBytes":0,"TableStatus":"ACTIVE"}}
2018/03/08 11:51:44 DEBUG: Request dynamodb/DescribeTable Details:
---[ REQUEST POST-SIGN ]-----------------------------
POST / HTTP/1.1
Host: dynamodb.eu-central-1.amazonaws.com
User-Agent: aws-sdk-go/2.0.0-preview.2 (go1.10; darwin; amd64) Waiter
Content-Length: 35
Accept-Encoding: identity
Authorization: AWS4-HMAC-SHA256 Credential=<redacted>/20180308/eu-central-1/dynamodb/aws4_request, SignedHeaders=accept-encoding;content-length;content-type;host;x-amz-date;x-amz-target, Signature=3a5964341374329c492fb4871c079e70e39040420abef226b9b73ebe2f428637
Content-Type: application/x-amz-json-1.0
X-Amz-Date: 20180308T105144Z
X-Amz-Target: DynamoDB_20120810.DescribeTable

{"TableName":"numbers-test-waiter"}
-----------------------------------------------------
2018/03/08 11:51:44 DEBUG: Response dynamodb/DescribeTable Details:
---[ RESPONSE ]--------------------------------------
HTTP/1.1 200 OK
Content-Length: 496
Connection: keep-alive
Content-Type: application/x-amz-json-1.0
Date: Thu, 08 Mar 2018 10:51:44 GMT
Server: Server
X-Amz-Crc32: 570748969
X-Amzn-Requestid: JIJ8H9SRKVE0GL5EP6G5TR4LTBVV4KQNSO5AEMVJF66Q9ASUAAJG


-----------------------------------------------------
2018/03/08 11:51:44 {"Table":{"AttributeDefinitions":[{"AttributeName":"number","AttributeType":"S"}],"CreationDateTime":1.520506292272E9,"ItemCount":0,"KeySchema":[{"AttributeName":"number","KeyType":"HASH"}],"ProvisionedThroughput":{"NumberOfDecreasesToday":0,"ReadCapacityUnits":1,"WriteCapacityUnits":1},"TableArn":"arn:aws:dynamodb:eu-central-1:<redacted>:table/numbers-test-waiter","TableId":"e319b9c0-0dd0-4777-bf12-4e3a210e41ed","TableName":"numbers-test-waiter","TableSizeBytes":0,"TableStatus":"ACTIVE"}}
2018/03/08 11:51:47 DEBUG: Request dynamodb/DescribeTable Details:
---[ REQUEST POST-SIGN ]-----------------------------
POST / HTTP/1.1
Host: dynamodb.eu-central-1.amazonaws.com
User-Agent: aws-sdk-go/2.0.0-preview.2 (go1.10; darwin; amd64) Waiter
Content-Length: 35
Accept-Encoding: identity
Authorization: AWS4-HMAC-SHA256 Credential=<redacted>/20180308/eu-central-1/dynamodb/aws4_request, SignedHeaders=accept-encoding;content-length;content-type;host;x-amz-date;x-amz-target, Signature=7e9df0dc63cf671d1d4f16389f523df68397c8973dbecd51b5ee9c9dc3cf9080
Content-Type: application/x-amz-json-1.0
X-Amz-Date: 20180308T105147Z
X-Amz-Target: DynamoDB_20120810.DescribeTable

{"TableName":"numbers-test-waiter"}
-----------------------------------------------------
2018/03/08 11:51:47 DEBUG: Response dynamodb/DescribeTable Details:
---[ RESPONSE ]--------------------------------------
HTTP/1.1 200 OK
Content-Length: 496
Connection: keep-alive
Content-Type: application/x-amz-json-1.0
Date: Thu, 08 Mar 2018 10:51:47 GMT
Server: Server
X-Amz-Crc32: 570748969
X-Amzn-Requestid: B06EHGQKB7H2RC1N1PQ0S7O5OFVV4KQNSO5AEMVJF66Q9ASUAAJG


-----------------------------------------------------
2018/03/08 11:51:47 {"Table":{"AttributeDefinitions":[{"AttributeName":"number","AttributeType":"S"}],"CreationDateTime":1.520506292272E9,"ItemCount":0,"KeySchema":[{"AttributeName":"number","KeyType":"HASH"}],"ProvisionedThroughput":{"NumberOfDecreasesToday":0,"ReadCapacityUnits":1,"WriteCapacityUnits":1},"TableArn":"arn:aws:dynamodb:eu-central-1:<redacted>:table/numbers-test-waiter","TableId":"e319b9c0-0dd0-4777-bf12-4e3a210e41ed","TableName":"numbers-test-waiter","TableSizeBytes":0,"TableStatus":"ACTIVE"}}
2018/03/08 11:51:50 DEBUG: Request dynamodb/DescribeTable Details:
---[ REQUEST POST-SIGN ]-----------------------------
POST / HTTP/1.1
Host: dynamodb.eu-central-1.amazonaws.com
User-Agent: aws-sdk-go/2.0.0-preview.2 (go1.10; darwin; amd64) Waiter
Content-Length: 35
Accept-Encoding: identity
Authorization: AWS4-HMAC-SHA256 Credential=<redacted>/20180308/eu-central-1/dynamodb/aws4_request, SignedHeaders=accept-encoding;content-length;content-type;host;x-amz-date;x-amz-target, Signature=29c2ed8bb7aa0eba1bfb80b4c355053348e9474197657b3d2ab3724b1fa258bb
Content-Type: application/x-amz-json-1.0
X-Amz-Date: 20180308T105150Z
X-Amz-Target: DynamoDB_20120810.DescribeTable

{"TableName":"numbers-test-waiter"}
-----------------------------------------------------
2018/03/08 11:51:50 DEBUG: Response dynamodb/DescribeTable Details:
---[ RESPONSE ]--------------------------------------
HTTP/1.1 200 OK
Content-Length: 496
Connection: keep-alive
Content-Type: application/x-amz-json-1.0
Date: Thu, 08 Mar 2018 10:51:50 GMT
Server: Server
X-Amz-Crc32: 570748969
X-Amzn-Requestid: HJ3NV2DPDSQAVMBSNOO256MI3JVV4KQNSO5AEMVJF66Q9ASUAAJG


-----------------------------------------------------
2018/03/08 11:51:50 {"Table":{"AttributeDefinitions":[{"AttributeName":"number","AttributeType":"S"}],"CreationDateTime":1.520506292272E9,"ItemCount":0,"KeySchema":[{"AttributeName":"number","KeyType":"HASH"}],"ProvisionedThroughput":{"NumberOfDecreasesToday":0,"ReadCapacityUnits":1,"WriteCapacityUnits":1},"TableArn":"arn:aws:dynamodb:eu-central-1:<redacted>:table/numbers-test-waiter","TableId":"e319b9c0-0dd0-4777-bf12-4e3a210e41ed","TableName":"numbers-test-waiter","TableSizeBytes":0,"TableStatus":"ACTIVE"}}
2018/03/08 11:51:53 DEBUG: Request dynamodb/DescribeTable Details:
---[ REQUEST POST-SIGN ]-----------------------------
POST / HTTP/1.1
Host: dynamodb.eu-central-1.amazonaws.com
User-Agent: aws-sdk-go/2.0.0-preview.2 (go1.10; darwin; amd64) Waiter
Content-Length: 35
Accept-Encoding: identity
Authorization: AWS4-HMAC-SHA256 Credential=<redacted>/20180308/eu-central-1/dynamodb/aws4_request, SignedHeaders=accept-encoding;content-length;content-type;host;x-amz-date;x-amz-target, Signature=e77726e4267edc486695f998818c2da7577460fae5949a4294fbe23bb2cc88ad
Content-Type: application/x-amz-json-1.0
X-Amz-Date: 20180308T105153Z
X-Amz-Target: DynamoDB_20120810.DescribeTable

{"TableName":"numbers-test-waiter"}
-----------------------------------------------------
2018/03/08 11:51:53 DEBUG: Response dynamodb/DescribeTable Details:
---[ RESPONSE ]--------------------------------------
HTTP/1.1 200 OK
Content-Length: 496
Connection: keep-alive
Content-Type: application/x-amz-json-1.0
Date: Thu, 08 Mar 2018 10:51:53 GMT
Server: Server
X-Amz-Crc32: 570748969
X-Amzn-Requestid: 97T3686KH97LNRSM0BH7LH9C6FVV4KQNSO5AEMVJF66Q9ASUAAJG


-----------------------------------------------------
2018/03/08 11:51:53 {"Table":{"AttributeDefinitions":[{"AttributeName":"number","AttributeType":"S"}],"CreationDateTime":1.520506292272E9,"ItemCount":0,"KeySchema":[{"AttributeName":"number","KeyType":"HASH"}],"ProvisionedThroughput":{"NumberOfDecreasesToday":0,"ReadCapacityUnits":1,"WriteCapacityUnits":1},"TableArn":"arn:aws:dynamodb:eu-central-1:<redacted>:table/numbers-test-waiter","TableId":"e319b9c0-0dd0-4777-bf12-4e3a210e41ed","TableName":"numbers-test-waiter","TableSizeBytes":0,"TableStatus":"ACTIVE"}}
2018/03/08 11:51:56 DEBUG: Request dynamodb/DescribeTable Details:
---[ REQUEST POST-SIGN ]-----------------------------
POST / HTTP/1.1
Host: dynamodb.eu-central-1.amazonaws.com
User-Agent: aws-sdk-go/2.0.0-preview.2 (go1.10; darwin; amd64) Waiter
Content-Length: 35
Accept-Encoding: identity
Authorization: AWS4-HMAC-SHA256 Credential=<redacted>/20180308/eu-central-1/dynamodb/aws4_request, SignedHeaders=accept-encoding;content-length;content-type;host;x-amz-date;x-amz-target, Signature=7168bf0c7cbc1fed88a8aec4d343579175aa208f798b608bbca03aabcbcc90b6
Content-Type: application/x-amz-json-1.0
X-Amz-Date: 20180308T105156Z
X-Amz-Target: DynamoDB_20120810.DescribeTable

{"TableName":"numbers-test-waiter"}
-----------------------------------------------------
2018/03/08 11:51:56 DEBUG: Response dynamodb/DescribeTable Details:
---[ RESPONSE ]--------------------------------------
HTTP/1.1 200 OK
Content-Length: 496
Connection: keep-alive
Content-Type: application/x-amz-json-1.0
Date: Thu, 08 Mar 2018 10:51:56 GMT
Server: Server
X-Amz-Crc32: 570748969
X-Amzn-Requestid: L04JFKBNH8GK3F0C1OIBIQ0KRFVV4KQNSO5AEMVJF66Q9ASUAAJG


-----------------------------------------------------
2018/03/08 11:51:56 {"Table":{"AttributeDefinitions":[{"AttributeName":"number","AttributeType":"S"}],"CreationDateTime":1.520506292272E9,"ItemCount":0,"KeySchema":[{"AttributeName":"number","KeyType":"HASH"}],"ProvisionedThroughput":{"NumberOfDecreasesToday":0,"ReadCapacityUnits":1,"WriteCapacityUnits":1},"TableArn":"arn:aws:dynamodb:eu-central-1:<redacted>:table/numbers-test-waiter","TableId":"e319b9c0-0dd0-4777-bf12-4e3a210e41ed","TableName":"numbers-test-waiter","TableSizeBytes":0,"TableStatus":"ACTIVE"}}
2018/03/08 11:51:59 DEBUG: Request dynamodb/DescribeTable Details:
---[ REQUEST POST-SIGN ]-----------------------------
POST / HTTP/1.1
Host: dynamodb.eu-central-1.amazonaws.com
User-Agent: aws-sdk-go/2.0.0-preview.2 (go1.10; darwin; amd64) Waiter
Content-Length: 35
Accept-Encoding: identity
Authorization: AWS4-HMAC-SHA256 Credential=<redacted>/20180308/eu-central-1/dynamodb/aws4_request, SignedHeaders=accept-encoding;content-length;content-type;host;x-amz-date;x-amz-target, Signature=8045d64b05f0084cfcab262bac98e316e8fd8e80469a77911abbc9b11393f481
Content-Type: application/x-amz-json-1.0
X-Amz-Date: 20180308T105159Z
X-Amz-Target: DynamoDB_20120810.DescribeTable

{"TableName":"numbers-test-waiter"}
-----------------------------------------------------
2018/03/08 11:51:59 DEBUG: Response dynamodb/DescribeTable Details:
---[ RESPONSE ]--------------------------------------
HTTP/1.1 200 OK
Content-Length: 496
Connection: keep-alive
Content-Type: application/x-amz-json-1.0
Date: Thu, 08 Mar 2018 10:51:59 GMT
Server: Server
X-Amz-Crc32: 570748969
X-Amzn-Requestid: UOPDDD44OOUT911OK7TTDHGONNVV4KQNSO5AEMVJF66Q9ASUAAJG


-----------------------------------------------------
2018/03/08 11:51:59 {"Table":{"AttributeDefinitions":[{"AttributeName":"number","AttributeType":"S"}],"CreationDateTime":1.520506292272E9,"ItemCount":0,"KeySchema":[{"AttributeName":"number","KeyType":"HASH"}],"ProvisionedThroughput":{"NumberOfDecreasesToday":0,"ReadCapacityUnits":1,"WriteCapacityUnits":1},"TableArn":"arn:aws:dynamodb:eu-central-1:<redacted>:table/numbers-test-waiter","TableId":"e319b9c0-0dd0-4777-bf12-4e3a210e41ed","TableName":"numbers-test-waiter","TableSizeBytes":0,"TableStatus":"ACTIVE"}}
--- FAIL: TestWaiter (27.83s)
	/Users/slaskis/Work/Department/Telness/tell-ess/backend/src/telness/pool/numbers/service_test.go:91: ResourceNotReady: exceeded wait attempts
FAIL
FAIL	telness/pool/numbers	27.851s
Error: Tests failed.
```

</details>

**Comment by slaskis** [comment] 2018-03-08 11:51
Same happens against dynamodb local

**Comment by jasdel** [comment] 2018-03-08 17:57
Thanks for creating this issue @slaskis is your application running against HEAD of the SDK or the `v2.0.0-preview.2` tag?  We fixed an issue with Waiters not working correctly in some cases and fixed in #102.  Could you try updating to HEAD and see if the issue is still occurring. This fix is not in a tagged release yet.

**Comment by slaskis** [comment] 2018-03-08 17:59
I have this in my Gopkg.lock:

```

[[projects]]
  name = "github.com/aws/aws-sdk-go-v2"
  packages = [
    "aws",
    "aws/awserr",
    "aws/defaults",
    "aws/ec2metadata",
    "aws/ec2rolecreds",
    "aws/endpointcreds",
    "aws/endpoints",
    "aws/external",
    "aws/signer/v4",
    "aws/stscreds",
    "internal/awsutil",
    "internal/sdk",
    "private/protocol",
    "private/protocol/json/jsonutil",
    "private/protocol/jsonrpc",
    "private/protocol/query",
    "private/protocol/query/queryutil",
    "private/protocol/rest",
    "private/protocol/xml/xmlutil",
    "service/dynamodb",
    "service/dynamodb/dynamodbattribute",
    "service/dynamodb/expression",
    "service/sts"
  ]
  revision = "b8e7febd4b80c6517240e473410b54d4e63fed1d"
  version = "v2.0.0-preview.2"
```

So I'm guessing its the tag (I didn't set anything, just ran `dep ensure`).

**Comment by slaskis** [comment] 2018-03-08 18:04
Yep, adding a constraint to `Gopkg.toml` seems to have fixed it, thanks!

```
[[constraint]]
  name = "github.com/aws/aws-sdk-go-v2"
  branch = "master"
```

**Comment by jasdel** [comment] 2018-03-08 18:07
Thanks for the update. I'm working on putting together a version bump for the SDK which will include this fix, along with others in a tagged release.

**Comment by jasdel** [comment] 2018-03-08 21:14
#147 is a tagged release which includes this and other fixes.

**Comment by jasdel** [comment] 2018-03-08 21:18
This tagged release has been merged in and is available.

**Closed by jasdel** 2018-03-08 21:18 UTC
