### ISSUE TITLE
Release service/dynamodb/v1.5.x that includes dynamodbiface interface

### ISSUE THREAD

**Issue by NaerChang2** [aws/aws-sdk-go-v2#1428] opened 2021-09-20 22:01 UTC
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [API reference](https://docs.aws.amazon.com/sdk-for-go/v2/api/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-go-v2/issues) and didn't find any solution
  

**Describe the bug**
Can you create a release tag for github.com/aws/aws-sdk-go-v2/service/dynamodb (ex: service/dynamodb/v1.5.2) that includes github.com/aws/aws-sdk-go-v2/service/dynamodb/dynamodbiface. Basically in the current release that code is not there yet.

**Version of AWS SDK for Go?**
github.com/aws/aws-sdk-go-v2 v1.9.1
service/dynamodb v1.5.1

**Version of Go (`go version`)?**
1.16

**To Reproduce (observed behavior)**
Short version of the test file.
```
package test

import (
	"errors"
	"net/http"
	"testing"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/service/dynamodb"
	"github.com/aws/aws-sdk-go-v2/service/dynamodb/dynamodbiface"
)

// A fakeDynamoDB instance. During testing, instatiate ItemGetter, then simply
// assign an instance of fakeDynamoDB to it.
type fakeDynamoDB struct {
	dynamodbiface.ClientAPI
	payload map[string]string // Store expected return values
	err     error
}

func TestDB(t *testing.T) {

}
```
Error:
github-lvs.corpzone.internalzone.com/mcafee/pwi-go-toolbox/pkg/test imports
        github.com/aws/aws-sdk-go-v2/service/dynamodb/dynamodbiface: module github.com/aws/aws-sdk-go-v2/service/dynamodb@latest found (v1.5.1), but does not contain package github.com/aws/aws-sdk-go-v2/service/dynamodb/dynamodbiface

**Expected behavior**
Build is successful

**Additional context**
The documentation make it sound like this feature is ready: https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/dynamodb/dynamodbiface.

**Comment by skmcgrail** [comment] 2021-09-20 23:14
Closing this issue as its a duplicate of https://github.com/aws/aws-sdk-go-v2/issues/786 where alternatives and reasoning around why these interface don't exist have been documented.

**Closed by skmcgrail** 2021-09-20 23:14 UTC
Labels: bug, needs-triage
