### ISSUE TITLE
missing PassthroughBehavior enum in types in apigateway(v1)

### ISSUE THREAD

**Issue by fgmarand** [aws/aws-sdk-go-v2#2755] opened 2024-08-21 08:29 UTC
### Pre-Migration Checklist

- [X] I've read the [Migration Guide](https://aws.github.io/aws-sdk-go-v2/docs/migrating/).
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) for similar migration issues.

### Go Version Used

Go 1.23 (irrelevant).

### Describe the Migration Issue

The constants `apigatewayv2.PassthroughBehaviorWhenNoMatch`, `apigatewayv2.PassthroughBehaviorNever` and `apigatewayv2.PassthroughBehaviorWhenNoTemplates` are missing from the v2 SDK.

As a consequence, the code in v2 uses plain magic constants in the source code instead of enum constants defined in the `types` package as happens for the other string constants.

### Code Comparison

`Client.PutIntegration` method takes a `PutIntegrationInput` struct with a `PassthroughBehavior` field that is a `*string` in both v1 and v2, so no difference.

### Observed Differences/Errors

One of the major changes in v2 is the use of the `types` package to store such enumerations and remove them as inline magic values, so one would expect these pre-existing constants to have been migrated, instead of just removed.

### Additional Context

The likely cause is that the SDK is actually missing any use case for these constants, because there does not appear to be unit tests around their behaviour.

**Comment by RanVaknin** [comment] 2024-08-21 23:29
Hi @fgmarand,

Are you referring to [these](https://github.com/aws/aws-sdk-go-v2/blob/main/service/apigatewayv2/types/enums.go#L197) enums?

In v2 the types are under `github.com/aws/aws-sdk-go-v2/service/<service-name>/types`

Thanks,
Ran~

**Comment by fgmarand** [comment] 2024-08-22 06:23
Hi @RanVaknin Indeed. The file where they should live is https://github.com/aws/aws-sdk-go-v2/blob/main/service/apigateway/types/enums.go but they haven't been created there.

**Comment by RanVaknin** [comment] 2024-08-22 17:05
Hi @fgmarand,

>Hi @RanVaknin Indeed. The file where they should live is [main/service/apigateway/types/enums.go](https://github.com/aws/aws-sdk-go-v2/blob/main/service/apigateway/types/enums.go?rgh-link-date=2024-08-22T06%3A23%3A58Z) but they haven't been created there.



These enums were only added to the APIGatewayV2 API, they were never a part of APIGW(v1) API. 
https://github.com/aws/aws-sdk-go-v2/blob/main/service/apigatewayv2/types/enums.go

You need to use the correct import to be able to use the enums. If APIGW(v1) supports sending those values as a "magic constants", then it reflects an unmodeled service side behavior. Since the AWS SDKs are all code-generated from each Service's API model, the SDK team cannot introduce any new enums because those would require and upstream change on the model level. Since the missing enums is for the legacy API (APIGWv1) the service team is unlikely to modify it. 

The solution here is to use APIGWv2 which has the modeled enums. (same exact behavior in Go SDK v1):

- [Go SDK v1 apigateway missing enums](https://github.com/aws/aws-sdk-go/blob/main/service/apigateway/api.go)
- [Go SDK v1 apigatewayv2 having enums](https://github.com/aws/aws-sdk-go/blob/02c1f723b528251a45068001bee8b56d904d7484/service/apigatewayv2/api.go#L20504-L20513)

- [Go SDK v2 apigateway missing enums](https://github.com/aws/aws-sdk-go-v2/blob/main/service/apigateway/types/enums.go)
- [Go SDK v2 apigatewayv2 having enums](https://github.com/aws/aws-sdk-go-v2/blob/main/service/apigatewayv2/types/enums.go#L197-201)

Thanks,
Ran~

**Comment by fgmarand** [comment] 2024-08-23 08:34
The situation is indeed similar in V1 and V2, as you explained, so it is not entirely a matter of V1 to V2 migration, although it is to some extent:

- the V1 and V2 API Gateway functions uses these exact three same values: `"WHEN_NO_MATCH"`, `"NEVER"`, or `"WHEN_NO_TEMPLATES"`, as documented on 
  - `GetIntegrationOutput.PassthroughBehavior`
  - `PutIntegrationInput.PassthroughBehavior`
  - `PutIntegrationOutput.PassthroughBehavior`
  - `UpdateIntegrationOutput.PassthroughBehavior`
  - `Integration.PassthroughBehavior`
- the constants defined in V2 `apigatewayv2.types` 
  - are the exact same three strings
  - are of type `types.PassthroughBehavior`, so cannot be used by API Gateway v1, as you mention, because those use a `*string` parameter
- to avoid discrepancy, in V1 the `apigatewayv2.types` constants could be used to provide the reference values because the types (`string` vs `*string`) and literal values matched, but the V2 constants are now a defined types `PassthroughBehavior` marking them as semantically specific.

But I guess the answer is "_Won't fix_" anyway ?

**Comment by RanVaknin** [comment] 2024-08-23 17:50
Hi @fgmarand ,

I'm really confused by your answer. For all intents and purposes lets only talk about the Go SDK v2 not v1. This issue was opened as a migration issue and I don't think it was classified correctly and that adds to my confusion.

The Go SDK has 2 apigateway API clients:

`apigateway` (v1) and `apigatewayv2` (v2). The backend API service of both versions might have backend support for sending `"WHEN_NO_MATCH"` or any of the other `PassthroughBehavior` enums as a literal strings, but in the `apigateway` model itself, did not model those enums therefore the SDK will not have those enums.

Since the SDK is generated from the model files of each API, and those are updated and maintained by the upstream service team, the SDK team cannot modify/ add / remove enums from the SDK. 

Since the issue is with `apigateway` and its a legacy API (if I had to guess it is still available to support legacy customers) and the `apigatewayv2` API offers the functionality you are looking for, there is very little chance that the APIGW service team will roll out changes something that is in perpetual maintenance mode and is supported in the new major version.

>But I guess the answer is "Won't fix" anyway ?

It's not that we wont fix it, it's that this is not actionable by our team since the SDK is code generated from that model file as I mentioned. This request normally would be routed to the backend service via our internal ticketing, but for the sake of transparency I would say that there is very little chance that this would get prioritized (legacy version, can be worked around using literal strings, non-blocking issue)

Is there anything stopping you from using `apigatewayv2`?

Thanks,
Ran~

**Comment by fgmarand** [comment] 2024-08-26 07:41
"Is there anything stopping you from using apigatewayv2" : this application was already written with `apigateway` when I started on it.  Guess I will have to convert it.

**Comment by fgmarand** [comment] 2024-08-26 08:03
Seems I had closed the issue too early: this has to be a "REST" API as outlined above, due to the missing features in v2 "HTTP" APIs.

**Comment by lucix-aws** [comment] 2024-08-26 12:41
We're getting off-topic here. I believe we've established that nothing is actually missing _in the Go SDK itself_ - that is to say, all of the content in the API models for apigatewayv1 and v2 are fully present their Go v2 SDK service clients. Therefore, there is no concrete SDK defect that is actionable for us. Closing accordingly.

**Closed** 2024-08-26 12:42 UTC
Labels: guidance, response-requested, p3
