### ISSUE TITLE
ECS List Tasks operation `startedBy` parameter can't be used with other arguments

### ISSUE THREAD

**Issue by jfagoagas** [aws/aws-sdk-go-v2#1893] opened 2022-10-24 15:40 UTC
### Describe the issue

The ECS List Tasks operation has a constraint when using the `startedBy` parameter because it can't be used with other arguments like `Family` or `LaunchType` because the AWS SDK throws the following exception:
```
An error occurred (InvalidParameterException) when calling the ListTasks operation: cannot specify startedBy with other arguments
```

There is no mention to this either in the AWS API documentation nor the SDK v2 for Go, but the API returns the above error.

I've opened this issue to include the above in the SDK documentation.

### Links

- https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/ecs#ListTasksInput
- https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_ListTasks.html

### AWS Go SDK V2 Module Versions Used

github.com/aws/aws-sdk-go-v2@v1.16.14 github.com/aws/smithy-go@v1.13.2
github.com/aws/aws-sdk-go-v2@v1.16.14 github.com/google/go-cmp@v0.5.8
github.com/aws/aws-sdk-go-v2@v1.16.14 github.com/jmespath/go-jmespath@v0.4.0
github.com/aws/aws-sdk-go-v2/aws/protocol/eventstream@v1.4.7 github.com/aws/smithy-go@v1.13.2
github.com/aws/aws-sdk-go-v2/config@v1.17.1 github.com/aws/aws-sdk-go-v2@v1.16.11
github.com/aws/aws-sdk-go-v2/config@v1.17.1 github.com/aws/aws-sdk-go-v2/credentials@v1.12.14
github.com/aws/aws-sdk-go-v2/config@v1.17.1 github.com/aws/aws-sdk-go-v2/feature/ec2/imds@v1.12.12
github.com/aws/aws-sdk-go-v2/config@v1.17.1 github.com/aws/aws-sdk-go-v2/internal/ini@v1.3.19
github.com/aws/aws-sdk-go-v2/config@v1.17.1 github.com/aws/aws-sdk-go-v2/service/sso@v1.11.17
github.com/aws/aws-sdk-go-v2/config@v1.17.1 github.com/aws/aws-sdk-go-v2/service/sts@v1.16.13
github.com/aws/aws-sdk-go-v2/config@v1.17.1 github.com/aws/smithy-go@v1.12.1
github.com/aws/aws-sdk-go-v2/config@v1.17.1 github.com/google/go-cmp@v0.5.8
github.com/aws/aws-sdk-go-v2/credentials@v1.12.14 github.com/aws/aws-sdk-go-v2@v1.16.11
github.com/aws/aws-sdk-go-v2/credentials@v1.12.14 github.com/aws/aws-sdk-go-v2/feature/ec2/imds@v1.12.12
github.com/aws/aws-sdk-go-v2/credentials@v1.12.14 github.com/aws/aws-sdk-go-v2/service/sso@v1.11.17
github.com/aws/aws-sdk-go-v2/credentials@v1.12.14 github.com/aws/aws-sdk-go-v2/service/sts@v1.16.13
github.com/aws/aws-sdk-go-v2/credentials@v1.12.14 github.com/aws/smithy-go@v1.12.1
github.com/aws/aws-sdk-go-v2/credentials@v1.12.14 github.com/google/go-cmp@v0.5.8
github.com/aws/aws-sdk-go-v2/feature/ec2/imds@v1.12.12 github.com/aws/aws-sdk-go-v2@v1.16.11
github.com/aws/aws-sdk-go-v2/feature/ec2/imds@v1.12.12 github.com/aws/smithy-go@v1.12.1
github.com/aws/aws-sdk-go-v2/feature/ec2/imds@v1.12.12 github.com/google/go-cmp@v0.5.8
github.com/aws/aws-sdk-go-v2/internal/configsources@v1.1.21 github.com/aws/aws-sdk-go-v2@v1.16.14
github.com/aws/aws-sdk-go-v2/internal/endpoints/v2@v2.4.15 github.com/aws/aws-sdk-go-v2@v1.16.14
github.com/aws/aws-sdk-go-v2/internal/endpoints/v2@v2.4.15 github.com/aws/smithy-go@v1.13.2
github.com/aws/aws-sdk-go-v2/internal/endpoints/v2@v2.4.15 github.com/google/go-cmp@v0.5.8
github.com/aws/aws-sdk-go-v2/internal/ini@v1.3.19 github.com/aws/aws-sdk-go-v2@v1.16.11
github.com/aws/aws-sdk-go-v2/internal/v4a@v1.0.12 github.com/aws/aws-sdk-go-v2@v1.16.14
github.com/aws/aws-sdk-go-v2/internal/v4a@v1.0.12 github.com/aws/smithy-go@v1.13.2
github.com/aws/aws-sdk-go-v2/internal/v4a@v1.0.12 github.com/google/go-cmp@v0.5.8
github.com/aws/aws-sdk-go-v2/service/ecs@v1.18.19 github.com/aws/aws-sdk-go-v2@v1.16.14
github.com/aws/aws-sdk-go-v2/service/ecs@v1.18.19 github.com/aws/aws-sdk-go-v2/internal/configsources@v1.1.21
github.com/aws/aws-sdk-go-v2/service/ecs@v1.18.19 github.com/aws/aws-sdk-go-v2/internal/endpoints/v2@v2.4.15
github.com/aws/aws-sdk-go-v2/service/ecs@v1.18.19 github.com/aws/smithy-go@v1.13.2
github.com/aws/aws-sdk-go-v2/service/ecs@v1.18.19 github.com/jmespath/go-jmespath@v0.4.0
github.com/aws/aws-sdk-go-v2/service/internal/accept-encoding@v1.9.8 github.com/aws/smithy-go@v1.13.2
github.com/aws/aws-sdk-go-v2/service/internal/checksum@v1.1.16 github.com/aws/aws-sdk-go-v2@v1.16.14
github.com/aws/aws-sdk-go-v2/service/internal/checksum@v1.1.16 github.com/aws/smithy-go@v1.13.2
github.com/aws/aws-sdk-go-v2/service/internal/checksum@v1.1.16 github.com/google/go-cmp@v0.5.8
github.com/aws/aws-sdk-go-v2/service/internal/presigned-url@v1.9.15 github.com/aws/aws-sdk-go-v2@v1.16.14
github.com/aws/aws-sdk-go-v2/service/internal/presigned-url@v1.9.15 github.com/aws/smithy-go@v1.13.2
github.com/aws/aws-sdk-go-v2/service/internal/presigned-url@v1.9.15 github.com/google/go-cmp@v0.5.8
github.com/aws/aws-sdk-go-v2/service/internal/s3shared@v1.13.15 github.com/aws/aws-sdk-go-v2@v1.16.14
github.com/aws/aws-sdk-go-v2/service/internal/s3shared@v1.13.15 github.com/aws/smithy-go@v1.13.2
github.com/aws/aws-sdk-go-v2/service/s3@v1.27.9 github.com/aws/aws-sdk-go-v2@v1.16.14
github.com/aws/aws-sdk-go-v2/service/s3@v1.27.9 github.com/aws/aws-sdk-go-v2/aws/protocol/eventstream@v1.4.7
github.com/aws/aws-sdk-go-v2/service/s3@v1.27.9 github.com/aws/aws-sdk-go-v2/internal/configsources@v1.1.21
github.com/aws/aws-sdk-go-v2/service/s3@v1.27.9 github.com/aws/aws-sdk-go-v2/internal/endpoints/v2@v2.4.15
github.com/aws/aws-sdk-go-v2/service/s3@v1.27.9 github.com/aws/aws-sdk-go-v2/internal/v4a@v1.0.12
github.com/aws/aws-sdk-go-v2/service/s3@v1.27.9 github.com/aws/aws-sdk-go-v2/service/internal/accept-encoding@v1.9.8
github.com/aws/aws-sdk-go-v2/service/s3@v1.27.9 github.com/aws/aws-sdk-go-v2/service/internal/checksum@v1.1.16
github.com/aws/aws-sdk-go-v2/service/s3@v1.27.9 github.com/aws/aws-sdk-go-v2/service/internal/presigned-url@v1.9.15
github.com/aws/aws-sdk-go-v2/service/s3@v1.27.9 github.com/aws/aws-sdk-go-v2/service/internal/s3shared@v1.13.15
github.com/aws/aws-sdk-go-v2/service/s3@v1.27.9 github.com/aws/smithy-go@v1.13.2
github.com/aws/aws-sdk-go-v2/service/s3@v1.27.9 github.com/google/go-cmp@v0.5.8
github.com/aws/aws-sdk-go-v2/service/secretsmanager@v1.15.19 github.com/aws/aws-sdk-go-v2@v1.16.12
github.com/aws/aws-sdk-go-v2/service/secretsmanager@v1.15.19 github.com/aws/aws-sdk-go-v2/internal/configsources@v1.1.19
github.com/aws/aws-sdk-go-v2/service/secretsmanager@v1.15.19 github.com/aws/aws-sdk-go-v2/internal/endpoints/v2@v2.4.13
github.com/aws/aws-sdk-go-v2/service/secretsmanager@v1.15.19 github.com/aws/smithy-go@v1.13.0
github.com/aws/aws-sdk-go-v2/service/ssm@v1.27.11 github.com/aws/aws-sdk-go-v2@v1.16.12
github.com/aws/aws-sdk-go-v2/service/ssm@v1.27.11 github.com/aws/aws-sdk-go-v2/internal/configsources@v1.1.19
github.com/aws/aws-sdk-go-v2/service/ssm@v1.27.11 github.com/aws/aws-sdk-go-v2/internal/endpoints/v2@v2.4.13
github.com/aws/aws-sdk-go-v2/service/ssm@v1.27.11 github.com/aws/smithy-go@v1.13.0
github.com/aws/aws-sdk-go-v2/service/ssm@v1.27.11 github.com/jmespath/go-jmespath@v0.4.0
github.com/aws/aws-sdk-go-v2/service/sso@v1.11.17 github.com/aws/aws-sdk-go-v2@v1.16.11
github.com/aws/aws-sdk-go-v2/service/sso@v1.11.17 github.com/aws/aws-sdk-go-v2/internal/configsources@v1.1.18
github.com/aws/aws-sdk-go-v2/service/sso@v1.11.17 github.com/aws/aws-sdk-go-v2/internal/endpoints/v2@v2.4.12
github.com/aws/aws-sdk-go-v2/service/sso@v1.11.17 github.com/aws/smithy-go@v1.12.1
github.com/aws/aws-sdk-go-v2/service/sts@v1.16.13 github.com/aws/aws-sdk-go-v2@v1.16.11
github.com/aws/aws-sdk-go-v2/service/sts@v1.16.13 github.com/aws/aws-sdk-go-v2/internal/configsources@v1.1.18
github.com/aws/aws-sdk-go-v2/service/sts@v1.16.13 github.com/aws/aws-sdk-go-v2/internal/endpoints/v2@v2.4.12
github.com/aws/aws-sdk-go-v2/service/sts@v1.16.13 github.com/aws/aws-sdk-go-v2/service/internal/presigned-url@v1.9.12
github.com/aws/aws-sdk-go-v2/service/sts@v1.16.13 github.com/aws/smithy-go@v1.12.1
github.com/aws/smithy-go@v1.13.2 github.com/google/go-cmp@v0.5.8
github.com/aws/smithy-go@v1.13.2 github.com/jmespath/go-jmespath@v0.4.0

**Comment by RanVaknin** [comment] 2022-10-24 18:00
Hi @jfagoagas ,

In order to confirm the issue can you please do the following:

- Include a code sample and clear reproduction steps.
- Try to run the same command from the CLI to see if the behavior is different there.

Documentation and API definitions are auto-generated from the Service Models of the different AWS services. The ECS team owns that documentation and this should be handled upstream with them. If you don't want to wait for me to reproduce, you are welcome to close this issue and use the `Feedback` tool at the top righthand corner of the documentation page:

<img width="1165" alt="image" src="https://user-images.githubusercontent.com/50976344/197593741-52683a3c-8274-4ca1-9560-390e6b225152.png">

Thanks,
Ran~

**Comment by jfagoagas** [comment] 2022-10-25 05:47
Hi @RanVaknin, thanks for your quick response.

Mi code sample is the following, as easy as modify the API documentation: https://github.com/aws/aws-sdk-go-v2/blob/main/service/ecs/api_op_ListTasks.go#L86-L88
```go
// The startedBy value to filter the task results with. Specifying a startedBy
// value limits the results to tasks that were started with that value.
// Take into consideration that this value can't be used with another arguments
// like Family or LaunchType
StartedBy *string
```


As you can see in the following image, the CLI behaviour is the same:
<img width="1712" alt="Screenshot 2022-10-25 at 07 39 28" src="https://user-images.githubusercontent.com/16007882/197692533-6989488e-db6a-4ac3-90c9-bf47eec77347.png">

**Comment by RanVaknin** [comment] 2022-10-26 18:08
@RanVaknin ,

Thank you for the repro through the CLI, this definitely helped. 

That piece of documentation that you want to change is auto-generated from the ECS service model. You can see the source [right here.](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_ListTasks.html#API_ListTasks_RequestSyntax)
It's identical to the documentation in the Go SDK because the SDK is built from that.

Even if we "edit" that documentation. The next time ECS will create a release, the SDK will be again generated with the old documentation, so this needs to change at the source.

I highly encourage you to use the [feedback tool](https://docs-feedback.aws.amazon.com/feedback.jsp?hidden_service_name=AmazonEC2ContainerService&topic_url=https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_ListTasks.html) so that they can fix that at the source.

I appreciate you engaging in the community in trying to make the SDKs better 😄 
All the best,
Ran~

**Closed by RanVaknin** 2022-10-26 18:08 UTC
Labels: documentation
