### ISSUE TITLE
Full DAX Support in aws-sdk-go-v2

### ISSUE THREAD

**Issue by nikhilmalhotra-verkada** [aws/aws-sdk-go-v2#2539] opened 2024-03-06 22:08 UTC
### Describe the feature

The Go (v2) SDK for DAX does not support any data level operations such as GetItem, PutItem, etc. With Go (v1) EOL being July 30, 2024, support is needed for DAX data level operations to fully migrate away from v1

### Use Case

Cannot fully migrate to Go (v2) SDK as support for data level DAX operations are missing

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS Go SDK V2 Module Versions Used

github.com/aws/aws-sdk-go-v2/service/dax 1.19.1

### Go version used

1.20

**Comment by lucix-aws** [comment] 2024-03-06 22:30
The DAX client is not owned by us. This is essentially a duplicate of https://github.com/aws/aws-dax-go/issues/2 and requests of this nature belong there.

**Closed by lucix-aws** 2024-03-06 22:30 UTC
Labels: feature-request, needs-triage

**Comment by juanique** [comment] 2024-03-07 07:06
"not owned by us", way to ship the org-chart to your cloud customers.

**Comment by miparnisari** [comment] 2024-05-10 22:59
@lucix-aws why is DAX a second-class citizen? It's a service offered by AWS, is it not? And this is the AWS SDK, is it not? Then it should support it.
