### ISSUE TITLE
Update DocDB model to add waiter for DBInstanceDeleted

### ISSUE THREAD

**Issue by quinyx-tjeerd** [aws/aws-sdk-go-v2#1370] opened 2021-08-05 12:30 UTC
**Is your feature request related to a problem? Please describe.**
Waiting for instances to be created / deleted takes time, so providing waiters is preferred 😅 

**Describe the solution you'd like**
updating of docdb models like @skmcgrail did for RDS (amongst others) in #1367

**Describe alternatives you've considered**
Making custom waiters works, but is not sustainable long term 😅 

**Additional context**
the above mentioned updating of models seemed to have led to the DBInstanceDeletedWaiter to become available for RDS. which was requested in #1344

**Comment by KaibaLopez** [comment] 2021-12-17 22:36
Kind of a duplicate of #1371 , Closing this one and keeping the other one open, thanks for bringing this up to us btw.

**Closed by KaibaLopez** 2021-12-17 22:36 UTC
Labels: v1-sync, feature-request
