### ISSUE TITLE
CcAddresses is useless when send email with ses raw email

### ISSUE THREAD

**Issue by lanjiexin** [aws/aws-sdk-go-v2#2167] opened 2023-06-30 10:33 UTC
### Describe the bug

When I am using github.com/aws/aws-sdk-go-v2/service/ses, the cc address set has no effect, and the cc address cannot receive email

### Expected Behavior

Expect cc address to receive email

### Current Behavior

cc address can not receive email

### Reproduction Steps

here is the code:

```go
`package email

import (
	"context"
	"fmt"
	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/config"
	"github.com/aws/aws-sdk-go-v2/service/ses"
	"log"
	"net/http"
	"strings"
)

func SendRawEmail(ctx context.Context, senderName, sender string, recipients, cc []string, replyTo, replyToName string, rawEmailData []byte) (string, error) {
	cfg, err := config.LoadDefaultConfig(ctx, config.WithRegion("ap-southeast-1"), config.WithHTTPClient(CreateHttpClientWithoutKeepAlive()))
	if err != nil {
		log.Println("[AWS SDK] Failed to load AWS config:", err)
		return "", err
	}

	svc := ses.NewFromConfig(cfg)

	// Create the input object
	input := &ses.SendRawEmailInput{
		Source: aws.String(senderName + " <" + sender + ">"),
		RawMessage: &ses.RawMessage{
			Data: rawEmailData,
		},
		Destinations: recipients,
	}

	if len(cc) > 0 {
		input.Destinations = append(input.Destinations, cc...)
	}

	output, err := svc.SendRawEmail(ctx, input)
	if err != nil {
		log.Println("[SES] Failed to send email:", err)
		return "", err
	}

	return *output.MessageId, nil
}

func CreateHttpClientWithoutKeepAlive() *http.Client {
	client := &http.Client{
		Transport: &http.Transport{
			DisableKeepAlives: true,
		},
	}

	return client
}

// Usage example:
func main() {
	rawEmailData := []byte("From: sender@example.com\nTo: recipient@example.com\nCc: cc1@example.com, cc2@example.com\nSubject: Test Email\nContent-Type: text/html\n\n<html><body><h1>Hello, this is a test email.</h1></body></html>")
	replyTo := "replyto@example.com"
	replyToName := "Reply To Name"

	messageID, err := SendRawEmail(context.Background(), "Sender Name", "sender@example.com", []string{"recipient@example.com"}, []string{"cc1@example.com", "cc2@example.com"}, replyTo, replyToName, rawEmailData)
	if err != nil {
		fmt.Println("Failed to send email:", err)
		return
	}

	fmt.Println("Email sent successfully. Message ID:", messageID)
}
``` 

### AWS Go SDK V2 Module Versions Used

github.com/aws/aws-sdk-go-v2 v1.18.1
github.com/aws/aws-sdk-go-v2/config v1.18.27
github.com/aws/aws-sdk-go-v2/service/ses v1.15.11

### Compiler and Version used

1.20

### Operating System and version

macOS

**Comment by lucix-aws** [comment] 2023-06-30 19:53
Unfortunately there is nothing actionable here for the Go SDK.

From our perspective, if we have successfully serialized and sent the request to the `ses` API, and the server returns a success response, the SDK is working correctly. From the above description, it appears that the SDK's request completes successfully (i.e. `SendRawEmail`'s returned `error` is `nil`) and the issue is that the service itself does not.

As far as debugging the issue is concerned, you will need to consult the available documentation resources for the `ses` service itself.

You may wish to try and recreate this behavior with another SDK such as boto3 or Java. If you discover a behavioral difference (e.g. the sent email reaches its intended recipients using Java v2, but NOT Go v2) please reach out in a new issue with your findings.

Closing since the SDK itself appears to be working as intended.

**Closed by lucix-aws** 2023-06-30 19:53 UTC
Labels: bug, needs-triage
