### ISSUE TITLE
use of internal package not allowed

### ISSUE THREAD

**Issue by kaihendry** [aws/aws-sdk-go-v2#108] opened 2018-01-20 08:20 UTC
### Version of AWS SDK for Go?
936d0f34ccd864b1f40b64e6910f2b1001713793

### Version of Go (`go version`)?
go version go1.9.2 linux/amd64

### What issue did you see?

`../aws-sdk-go-v2/service/s3/api.go:11:2: use of internal package not allowed
`
### Steps to reproduce

https://godoc.org/github.com/aws/aws-sdk-go-v2/service/s3#example-S3-ListBucketsRequest-Shared00
http://play.golang.org/p/BBbTp6n8sCR

**Comment by kaihendry** [comment] 2018-01-25 09:09
I just did a `/home/ec2-user/go/src/github.com/kaihendry/bucketlist $ go get  .` on a fresh EC2 AmazonLinux 2 instance with golang & git installed, and same issue.

    ../aws-sdk-go-v2/service/s3/api.go:11:2: use of internal package not allowed

Are you not able to reproduce? :thinking:

**Comment by xibz** [comment] 2018-01-25 18:01
@kaihendry - Do you have anything vendored? I would also suggest cleaning out your `pkg` folder in your `GOPATH`. I don't believe this is an SDK issue, but an environment issue as I cannot reproduce this in a clean work environment. I am going to go ahead and close this. If you are still having issues, I would suggest asking on [stackoverflow](https://stackoverflow.com/questions/tagged/aws-sdk-go) or [gitter](https://gitter.im/aws/aws-sdk-go) as people that may have run into this exact issue could help you out :).

**Closed by xibz** 2018-01-25 18:01 UTC
Labels: Dependency

**Comment by kaihendry** [comment] 2018-01-31 02:41
I created a screen cast where I go from scratch with Amazon Linux 2. What am I missing? https://static.spuul.com/devops/2018-01-31/108.mp4

**Comment by jasdel** [comment] 2018-01-31 17:44
@kaihendry thanks a for the update and reproduction of the issue you're running into. Based on the console output it looks like the `github.com/kaihendry/bucketlist` application is referencing the `aws-sdk-go-v2` in the `github.com/kaihendry/aws-sdk-go-v2` folder. I'm guessing this is your fork of the v2 SDK.

I think this is failing the `bucketlist` application is importing the v2 SDK from the `github.com/kaihendry/aws-sdk-go-v2` path. Not the `github.com/aws/aws-sdk-go-v2` path. I think this is what is causing the internal import error. If you're `bucketlist` package is updated to import the v2 SDK from `github.com/aws/aws-sdk-go-v2` it will resolve your issue.

If you're using `dep` you can configure the lock file to substitute a repository for another. This would allow you to use your fork of the v2 SDK without changing the import path in your application. See the [Dependency rules](https://golang.github.io/dep/docs/Gopkg.toml.html#dependency-rules-constraint-and-override) section of the go `dep` tool for information on providing an alternative repo `source` for an import path.

I think the constraint for you would be something like:

```toml
[[constraint]]
  # Required: the root import path of the project being constrained.
  name = "github.com/aws/aws-sdk-go-v2"

  # An alternate location (URL or import path) for the project's source.
  source = "github.com/kaihendry/aws-sdk-go-v2.git"
```

Alternatively, if you will not be using `dep` and you want to use your fork of the SDK in your application the best way is to either symlink your fork of the SDK into the correct folder.

```sh
cd $GOPATH
mkdir -p src/github.com/kaihendry/ src/github.com/aws
git clone github.com/kaihendry/aws-sdk-go-v2 src/github.com/kaihendry/aws-sdk-go-v2
ln -s src/github.com/kaihendry/aws-sdk-go-v2 src/github.com/aws/aws-sdk-go-v2

git clone github.com/kaihendry/bucketlist src/github.com/kaihendry/bucketlist

cd src/github.com/kaihendry/bucketlist
go get .
```

**Comment by kaihendry** [comment] 2018-02-01 01:23
Argh, sorry for the noise. Can't believe I didn't notice that issue with my imports!!!
